---
.travis.yml:
  script: "\"bundle exec rake validate && bundle exec rake lint && bundle exec rake spec SPEC_OPTS='--color --format documentation'\""
  extras:
    - rvm: 1.9.3
      env: PUPPET_GEM_VERSION="3.4.0"
Gemfile:
  supports_windows: true
Rakefile:
  unmanaged: true
spec/spec_helper.rb:
  unmanaged: true
appveyor.yml:
  matrix_extras:
    - PUPPET_GEM_VERSION: 3.4.0
      RUBY_VER: 193
  test_script:
    - "'bundle exec puppet apply -e \"user {''Administrator'': ensure=>present, password => ''Th!s1sS#cur3@@@2129021'', groups=>[''Administrators''],}\" && exit 0'"
    - 'bundle exec rspec spec/unit spec/integration -fd -b'
