---
.gitignore:
  required:
    - ---.project

.gitlab-ci.yml:
  delete: true

.rubocop.yml:
   default_configs:
    inherit_from: .rubocop_todo.yml

appveyor.yml:
  matrix_extras:
    - PUPPET_GEM_VERSION: ~> 6.0
      RUBY_VERSION: 25
      CHECK: parallel_spec
    - PUPPET_GEM_VERSION: ~> 6.0
      RUBY_VERSION: 25-x64
      CHECK: parallel_spec

Gemfile:
  optional:
    ':development':
      - gem: net-telnet
        version: '0.1.0'
        condition: "Gem::Version.new(RUBY_VERSION.dup) < Gem::Version.new('2.3.0')"
      - gem: net-telnet
        condition: "Gem::Version.new(RUBY_VERSION.dup) >= Gem::Version.new('2.3.0')"
  required:
    ':system_tests':
      - gem: 'puppet-module-posix-system-r#{minor_version}'
        platforms: ruby
      - gem: 'puppet-module-win-system-r#{minor_version}'
        platforms:
          - mswin
          - mingw
          - x64_mingw
      - gem: beaker-testmode_switcher
        version: '~> 0.4'
      - gem: master_manipulator
      - gem: puppet-blacksmith
        version: '~> 3.4'

spec/default_facts.yml:
  unmanaged: true

spec/spec_helper.rb:
  mock_with: ':rspec'
  coverage_report: true